-- ■■■ 팀 별 실습 수행 과제 ■■■--

-- HR 샘플 스키마 ERD를 이용한 테이블 재구성~!!!

-- 팀별로... HR스키마에 있는 기본 테이블(7개)
-- COUNTRIES / DEPARTMENTS / EMPLOYEES / JOB_HISTORY / JOBS / LOCATIONS / REGIONS
-- 을 똑~~~~~~~ 같이 새로 구성한다.

-- 단, 생성하는 테이블 이름은 『테이블명+팀번호』
-- COUNTRIES4 / DEPARTMENTS4 / EMPLOYEES4 / JOB_HISTORY4 / JOBS4 / LOCATIONS4 / REGIONS4
-- 와 같이 구성한다.

-- 1. 기존 대상 테이블들의 정보 수집
-- 2. 테이블 생성(컬럼이름, 자료형, DEFAULT 표현식, NOT NULL 등 ...)
-- 3. 제약조건 설정(PK, UK, FK, CK, ...)
-- 4. 작성 후 데이터 입력

-- 제출 항목
--   - 20220304_02_hr(4팀_팀과제).sql
--   - 20220304_02_hr(4팀_팀과제) 수행후기.txt

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DEPARTMENTS';

SELECT *
FROM DEPARTMENTS4;

/*
10	Administration	200	1700
20	Marketing	201	1800
*/

DESC DEPARTMENTS4;

-- DEPARTMENTS4


/*
TABLE_NAME : DEPARTMENTS
                                COLUMN_NAME     SEARCH_CONDITION                    DELETE_RULE
HR	DEPT_NAME_NN(NOT NULL)		DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK(PRIMARY KEY)		DEPARTMENT_ID	(NULL)	
HR	DEPT_LOC_FK(FOREIGN KEY)	LOCATION_ID		(NULL)                               NO ACTION
HR	DEPT_MGR_FK(FOREIGN KEY)	MANAGER_ID		(NULL)                               NO ACTION

이름              널?       유형           
--------------- -------- ------------ 
DEPARTMENT_ID   NOT NULL NUMBER(4)              
DEPARTMENT_NAME NOT NULL VARCHAR2(30) 
MANAGER_ID               NUMBER(6)          CONSTRAINT DEPT_MGR_FK4 REFERENCES EMPLOYEES4(EMPLOYEE_ID) 이거 해야함  
LOCATION_ID              NUMBER(4)          CONSTRAINT DEPT_LOC_FK4 REFERENCES LOCATIONS4(LOCATION_ID) 
*/





SELECT DATA_DEFAULT
FROM user_tab_columns 
WHERE table_name='DEPARTMENTS';

SELECT COLUMN_NAME, NULLABLE
FROM user_tab_columns 
WHERE table_name='DEPARTMENTS';


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DEPARTMENTS4';
/*
확인/ 밑에 두개 추가해야함
HR	DEPT_NAME_NN4	DEPARTMENTS4	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK4	DEPARTMENTS4	P	DEPARTMENT_ID		

HR	DEPT_NAME_NN	DEPARTMENTS	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK	DEPARTMENTS	P	DEPARTMENT_ID		
HR	DEPT_LOC_FK	DEPARTMENTS	R	LOCATION_ID		NO ACTION
HR	DEPT_MGR_FK	DEPARTMENTS	R	MANAGER_ID		NO ACTION
*/


--------------------------------------------------------------------------------
-- DEPARTMENTS4테이블 생성
CREATE TABLE DEPARTMENTS4(
    DEPARTMENT_ID   NUMBER(4)       CONSTRAINT DEPT_ID_PK4 PRIMARY KEY
,   DEPARTMENT_NAME VARCHAR2(30)    CONSTRAINT DEPT_NAME_NN4 NOT NULL
,   MANAGER_ID      NUMBER(6)       
,   LOCATION_ID     NUMBER(4)       
);
--==>> Table DEPARTMENTS4이(가) 생성되었습니다.

-- 데이터 입력
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(10, 'Administration', 200, 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(20, 'Marketing', 201, 1800);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(30, 'Purchasing', 114, 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(40, 'Human Resources', 203, 2400);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(50, 'Shipping', 121, 1500);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(60, 'IT', 103, 1400);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(70, 'Public Relations', 204, 2700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(80, 'Sales', 145, 2500);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(90, 'Executive', 100, 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(100, 'Finance', 108, 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
       VALUES(110, 'Accounting', 205, 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(120, 'Treasury', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(130, 'Corporate Tax', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(140, 'Control And Credit', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(150, 'Shareholder Services', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(160, 'Benefits', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(170, 'Manufacturing', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(180, 'Construction', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(190, 'Contracting', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(200, 'Operations', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(210, 'IT Support', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(220, 'NOC', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(230, 'IT Helpdesk', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(240, 'Government Sales', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(250, 'Retail Sales', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(260, 'Recruiting', 1700);
INSERT INTO DEPARTMENTS4(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
       VALUES(270, 'Payroll', 1700);


-- 추후에 FOREIGN KEY 지정하기
ALTER TABLE DEPARTMENTS4 
ADD CONSTRAINT DEPT_LOC_FK4 FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS4(LOCATION_ID); 

ALTER TABLE DEPARTMENTS4 
ADD CONSTRAINT DEPT_MGR_FK4 FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES4(EMPLOYEE_ID); 


-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DEPARTMENTS4';
/*
원본
HR	DEPT_NAME_NN	DEPARTMENTS	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK	DEPARTMENTS	P	DEPARTMENT_ID		
HR	DEPT_LOC_FK	DEPARTMENTS	R	LOCATION_ID		NO ACTION
HR	DEPT_MGR_FK	DEPARTMENTS	R	MANAGER_ID		NO ACTION

FOREIGN KEY 추가 전
HR	DEPT_NAME_NN4	DEPARTMENTS4	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK4	DEPARTMENTS4	P	DEPARTMENT_ID		
*/

SELECT *
FROM DEPARTMENTS4;

COMMIT;

-------------------------------------------------------------------------------------------------

SELECT *
FROM EMPLOYEES;

DESC EMPLOYEES;








INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(169, 'Harrison', 'Bloom', 'HBLOOM', '011.44.1343.829268', '2006-03-23', 'SA_REP', 10000, 0.2, 148, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(170, 'Tayler', 'Fox', 'TFOX', '011.44.1343.729268', '2006-01-24', 'SA_REP', 9600, 0.2, 148, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(171, 'William', 'Smith', 'WSMITH', '011.44.1343.629268', '2007-02-23', 'SA_REP', 7400, 0.15, 148, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(172, 'Elizabeth', 'Bates', 'EBATES', '011.44.1343.529268', '2007-03-24', 'SA_REP', 7300, 0.15, 148, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(173, 'Sundita', 'Kumar', 'SKUMAR', '011.44.1343.329268', '2008-04-21', 'SA_REP', 6100, 0.1, 148, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(174, 'Ellen', 'Abel', 'EABEL', '011.44.1644.429267', '2004-05-11', 'SA_REP', 11000, 0.3, 149, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(175, 'Alyssa', 'Hutton','AHUTTON', '011.44.1644.429266', '2005-03-19', 'SA_REP', 8800, 0.25, 149, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(176, 'Jonathon', 'Taylor','JTAYLOR', '011.44.1644.429265', '2006-03-24', 'SA_REP', 8600, 0.2, 149, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(177, 'Jack', 'Livingston','JLIVINGS', '011.44.1644.429264', '2006-04-23', 'SA_REP', 8400, 0.2, 149, 80);
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(178, 'Kimberely', 'Grant','KGRANT', '011.44.1644.429263', '2007-05-24', 'SA_REP', 7000, 0.15, 149, NULL);
79번부터 올라가기
INSERT INTO EMPLOYEES4 (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER 
          , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES(169, 'Harrison', 'Bloom', 'HBLOOM', '011.44.1343.829268', '2006-03-23', 'SA_REP', 10000, 0.2, 148, 80);




--------------------------------------------------------------------------------------

EMPLOYEES4 코드


CREATE TABLE EMPLOYEES4
( EMPLOYEE_ID           NUMBER(6)
, FIRST_NAME             VARCHAR2(20)
, LAST_NAME              VARCHAR2(25)       NOT NULL
, EMAIL                       VARCHAR2(25)       NOT NULL
, PHONE_NUMBER       VARCHAR2(20)
, HIRE_DATE                DATE                      NOT NULL
, JOB_ID                      VARCHAR2(10)        NOT NULL
, SALARY                    NUMBER(8, 2)
, COMMISSION_PCT    NUMBER(2, 2)
, MANAGER_ID            NUMBER(6)
, DEPARTMENT_ID      NUMBER(4)
);
--==>> Table EMPLOYEES4이(가) 생성되었습니다.

-- 제약조건 추가 (NOT NULL FOREIGN KEY 빼고)
ALTER TABLE EMPLOYEES4
ADD (CONSTRAINT EMP4_SALARY_MIN CHECK(SALARY > 0)
        , CONSTRAINT EMP4_EMAIL_UK UNIQUE(EMAIL)
        , CONSTRAINT EMP4_EMP_ID_PK PRIMARY KEY(EMPLOYEE_ID));
--==>> Table EMPLOYEES4이(가) 변경되었습니다.

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'EMPLOYEES4';

-- 제약조건 이름 변경
ALTER TABLE EMPLOYEES4
RENAME CONSTRAINT SYS_C007084 TO EMP4_LAST_NAME_NN;

ALTER TABLE EMPLOYEES4
RENAME CONSTRAINT SYS_C007085 TO EMP4_EMAIL_NN;

ALTER TABLE EMPLOYEES4
RENAME CONSTRAINT SYS_C007086 TO EMP4_HIRE_DATE_NN;

ALTER TABLE EMPLOYEES4
RENAME CONSTRAINT SYS_C007087 TO EMP4_JOB_ID_NN;


-- 데이터만 복사
INSERT INTO EMPLOYEES4 
SELECT * 
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES;



-- 제약조건 FOREIGN KEY 추가
ALTER TABLE EMPLOYEES4
ADD (CONSTRAINT EMP4_DEPT_FK FOREIGN KEY(DEPARTMENT_ID)
                                                          REFERENCES DEPARTMENTS4
       , CONSTRAINT EMP4_JOB_FK FOREIGN KEY(JOB_ID)
                                                       REFERENCES JOBS4
       , CONSTRAINT EMP4_MANAGER_FK FOREIGN KEY(MANAGER_ID)
                                                                 REFERENCES DEPARTMENTS4);
                                                                 
                                                                 
                                                                 
ROLLBACK;