SELECT USER
FROM DUAL;
--==>>TEAM4



--------------------------------------------------------------------------------




-- 2
   -- 수정  끝나는 날 이후에 수정 불가 (끝나는날 이후(오늘) 오류) -> 오늘-날 > 0
   -- 삭제  끝나는 날 이전에 삭제 불가 (끝나는날 이전(오늘) 오류) -> 오늘-날 < 0
-- ○ COURSE OPEN 교수 삭제 프로시저
CREATE OR REPLACE PROCEDURE PRC_OP_COU_TC_DELETE
( V_OP_COURSE_CODE     IN COURSE_OPEN.OP_COURSE_CODE%TYPE
)
IS
    V_END_DATE   COURSE_OPEN.END_DATE%TYPE;
    V_TC_CODE   TEACHER_REGISTER.TEACHER_CODE%TYPE;
    V_CHECK_DATE    NUMBER;
    
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    SELECT END_DATE INTO V_END_DATE
      FROM COURSE_OPEN
     WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
    
    V_CHECK_DATE := TO_NUMBER(SYSDATE - V_END_DATE);
    -- 수강 기간중에 강사 삭제시 에러 발생
    IF (V_CHECK_DATE < 0)
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    SELECT NAME INTO V_TC_CODE
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = -1;
    
    
    UPDATE COURSE_OPEN
    SET TEACHER_CODE = V_TC_CODE
    WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
    
    EXCEPTION
    WHEN USER_DEFINE_ERROR
        THEN RAISE_APPLICATION_ERROR(-20015,'교수를 삭제할 수 없습니다. 교수를 변경하세요.');
             ROLLBACK;
    WHEN OTHERS
        THEN ROLLBACK;
        
    COMMIT;

END;



CREATE OR REPLACE PROCEDURE PRC_OP_COU_TEA_EDIT
( V_OP_COURSE_CODE    IN COURSE_OPEN.OP_COURSE_CODE%TYPE
, V_NEWTEA_CODE       IN COURSE_OPEN.TEACHER_CODE%TYPE  
)
IS 
    V_END_DATE          COURSE_OPEN.END_DATE%TYPE;
    V_CHECK_DATE        NUMBER;
    
     USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    SELECT END_DATE INTO V_END_DATE
      FROM COURSE_OPEN
     WHERE COURSE_OPEN.OP_COURSE_CODE = V_OP_COURSE_CODE;

    V_CHECK_DATE := TO_NUMBER(SYSDATE - V_END_DATE);
    
    IF(V_CHECK_DATE > 0 )
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    UPDATE COURSE_OPEN 
    SET  TEACHER_CODE = V_NEWTEA_CODE and course_code = v_course_code and classroom
    WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
     -- 실행 구문;
        
    EXCEPTION
    WHEN USER_DEFINE_ERROR
        THEN RAISE_APPLICATION_ERROR(-20012,'해당 과정이 끝나 교수를 변경할 수 없습니다.');
             ROLLBACK;
    WHEN OTHERS
        THEN ROLLBACK;
        
    COMMIT;
END;

SELECT *
FROM VIEW_CONSTCHECK;

--○ 테이블조회
SELECT *
FROM USER_TABLES;

DESC SUBJECT;

-- 출력 정보 : 과정명(COURSE(COURSE_OPEN.COURSE_CODE)), 강의실(CLASSROOM_REGISTER(COURSE_OPEN.CLASSROOM_CODE)), 
--             과목명(SUBJECT(SUBJECT_OPEN.SUBJECT_CODE)), 기간(COURSE_OPEN), 교재명(TEXTBOOK(SUBJECT_OPEN.SUBJECT_CODE)), 
--             교수자명(TEACHER_REGISTER(TEACHER_CODE)) -SELECT - 윤태 진행중

-- 과정개설코드를 받으면 과정명을 반환하는 함수
CREATE OR REPLACE FUNCTION FN_COURSE_NAME(V_OP_COURSE_CODE VARCHAR2)
RETURN VARCHAR2
IS
    V_COURSE_CODE   COURSE.COURSE_CODE%TYPE;
    V_COURSE_NAME   COURSE.COURSE_NAME%TYPE;
BEGIN
    SELECT COURSE_CODE INTO V_COURSE_CODE
      FROM COURSE_OPEN
     WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
    
    SELECT COURSE_NAME INTO V_COURSE_NAME
      FROM COURSE
     WHERE COURSE_CODE = V_COURSE_CODE;
     
     RETURN V_COURSE_NAME;
END;

