SELECT USER
  FROM DUAL;
  
CREATE TABLE STUDENT_REGISTER
(STUDENT_CODE    VARCHAR2(10)
,ID              VARCHAR2(20)
,PASSWORD        VARCHAR2(30) 
,NAME            VARCHAR2(20)
,SSN             VARCHAR2(13)
,REGISTER_DATE   DATE            
);
