SELECT USER
  FROM DUAL;
  
CREATE TABLE STUDENT_REGISTER
(STUDENT_CODE    VARCHAR2(10)
,ID              VARCHAR2(20)
,PASSWORD        VARCHAR2(30) 
,NAME            VARCHAR2(20)
,SSN             VARCHAR2(13)
,REGISTER_DATE   DATE            
);

------------------------------------------------

--○ 수강신청 테이블 생성(REG_COU)
CREATE TABLE COURSE_REGISTER
( REG_COURSE_CODE   VARCHAR2(10)   CONSTRAINT REG_COU_CODE_PK       PRIMARY KEY 
, OP_COURSE_CODE    VARCHAR2(10)   CONSTRAINT REG_COU_COU_CODE_NN   NOT NULL
, STUDENT_CODE      VARCHAR2(10)   CONSTRAINT REG_COU_STD_CODE_NN   NOT NULL
, REG_COURSE_DATE   DATE           DEFAULT SYSDATE
);

-- 수강신청 테이블 FK 추가
ALTER TABLE COURSE_REGISTER
ADD ( CONSTRAINT REG_COU_COU_CODE_FK FOREIGN KEY(OP_COURSE_CODE)
                 REFERENCES COURSE_OPEN(OP_COURSE_CODE)
    , CONSTRAINT TEG_COU_STD_CODE_FK FOREIGN KEY(STUDENT_CODE)
                 REFERENCES STUDENT_REGISTER(STUDENT_CODE) );



--○ 중도탈락 테이블 생성(DR_STD)
CREATE TABLE STUDENT_DROP
( DROP_CODE         VARCHAR2(10)    CONSTRAINT DR_STD_CODE_PK   PRIMARY KEY
, REG_COURSE_CODE   VARCHAR2(10)    CONSTRAINT DR_STD_COU_CODE  NOT NULL
, DR_REASON_CODE    NUMBER
, DROP_DATE         DATE            DEFAULT SYSDATE
);

-- 중도탈락 테이블 FK 추가
ALTER TABLE STUDENT_DROP
ADD ( CONSTRAINT DR_STD_COU_CODE_FK FOREIGN KEY(REG_COURSE_CODE)
                 REFERENCES COURSE_REGISTER(REG_COURSE_CODE)
    , CONSTRAINT DR_STD_RE_CODE_FK FOREIGN KEY(DR_REASON_CODE)
                 REFERENCES DROP_REASON(DR_REASON_CODE));
                 



                 